services:
  db:
    image: mariadb
    volumes:
      - "./db_data:/var/lib/mysql"
    ports:
      - "13306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb_password
      MARIADB_DATABASE: ese
  minio:
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    command: ["server", "/data", "--console-address", ":9090"]
    volumes:
      - "./minio:/data"
    environment:
      - MINIO_ROOT_USER=minio_root
      - MINIO_ROOT_PASSWORD=minio_password
      - MINIO_DOMAIN=minio
    ports:
      - "9000:9000"
      - "9090:9090"
  createbuckets:
    image: minio/mc:RELEASE.2022-12-24T15-21-38Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minio_root minio_password;
      mc mb --ignore-existing minio/ese-noodles;
      "

volumes:
  minio:
    driver: local